import sqlite3
import os

# Define the database file name
DB_FILE = "enterprise.db"

def initialize_database():
    """
    Connects to the SQLite database (creates it if it doesn't exist),
    creates the schema tables, and populates them with sample business data.
    """
    print(f"Connecting to database: {DB_FILE}...")
    
    # sqlite3.connect() opens a connection to the SQLite database file.
    # If the file 'enterprise.db' does not exist in the current directory, SQLite will create it automatically.
    conn = sqlite3.connect(DB_FILE)
    
    # A cursor object allows us to execute SQL statements and retrieve results from the database.
    cursor = conn.cursor()
    
    # =========================================================================
    # CREATE TABLES
    # =========================================================================
    
    # 1. CREATE EMPLOYEES TABLE
    # This stores info about employees. We use typical types:
    # - INTEGER PRIMARY KEY AUTOINCREMENT: A unique integer ID that increments automatically for each row.
    # - TEXT: For string data.
    # - REAL: For decimal numbers (like salaries).
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS employees (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        department TEXT NOT NULL,
        role TEXT NOT NULL,
        salary REAL NOT NULL
    );
    """)
    
    # 2. CREATE EXPENSES TABLE
    # This table stores business spending.
    # We store the date as TEXT in ISO 8601 format (YYYY-MM-DD), which SQLite handles easily.
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS expenses (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        date TEXT NOT NULL,
        category TEXT NOT NULL,
        amount REAL NOT NULL,
        description TEXT NOT NULL,
        approved_by TEXT NOT NULL
    );
    """)
    
    # 3. CREATE SALES TABLE
    # This stores revenue generated by software license or services sales.
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS sales (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        date TEXT NOT NULL,
        product TEXT NOT NULL,
        quantity INTEGER NOT NULL,
        unit_price REAL NOT NULL,
        total_amount REAL NOT NULL
    );
    """)
    
    print("Tables created successfully.")
    
    # =========================================================================
    # SEED DATA
    # =========================================================================
    # We want to clear any existing records before seeding so that we don't end up with duplicate rows
    # if we run the script multiple times.
    cursor.execute("DELETE FROM employees;")
    cursor.execute("DELETE FROM expenses;")
    cursor.execute("DELETE FROM sales;")
    
    # Seed Employees
    employees_data = [
        ("Alice Johnson", "Management", "CEO", 150000.0),
        ("Bob Smith", "Engineering", "Senior Software Engineer", 110000.0),
        ("Charlie Brown", "Engineering", "QA Engineer", 75000.0),
        ("Diana Prince", "Sales", "Sales Director", 95000.0),
        ("Evan Wright", "Sales", "Account Executive", 65000.0),
        ("Fiona Gallagher", "Marketing", "Marketing Specialist", 60000.0),
        ("George Costanza", "HR", "HR Assistant", 50000.0)
    ]
    cursor.executemany(
        "INSERT INTO employees (name, department, role, salary) VALUES (?, ?, ?, ?);",
        employees_data
    )
    
    # Seed Expenses
    # These represent transactions that occurred over the last couple of months.
    expenses_data = [
        ("2026-05-10", "Software", 1200.00, "Monthly AWS hosting invoice", "Alice Johnson"),
        ("2026-05-15", "Marketing", 5000.00, "Google Ads campaign for Q2 launch", "Diana Prince"),
        ("2026-05-20", "Office Supplies", 350.00, "Ergonomic chairs for new devs", "George Costanza"),
        ("2026-05-25", "Travel", 850.00, "Flights to annual sales conference", "Diana Prince"),
        ("2026-06-01", "Software", 1200.00, "Monthly AWS hosting invoice", "Alice Johnson"),
        ("2026-06-05", "Software", 450.00, "Slack Enterprise grid license", "Alice Johnson"),
        ("2026-06-12", "Marketing", 2500.00, "Sponsorship for TechConf 2026", "Diana Prince"),
        ("2026-06-18", "Office Supplies", 120.00, "Coffee pods and snacks for pantry", "George Costanza"),
        ("2026-06-25", "Rent", 3000.00, "Office space rent - June", "Alice Johnson"),
        ("2026-07-01", "Software", 1200.00, "Monthly AWS hosting invoice", "Alice Johnson"),
    ]
    cursor.executemany(
        "INSERT INTO expenses (date, category, amount, description, approved_by) VALUES (?, ?, ?, ?, ?);",
        expenses_data
    )
    
    # Seed Sales
    # These represent sales revenue.
    sales_data = [
        ("2026-05-12", "Enterprise Cloud License", 2, 5000.00, 10000.00),
        ("2026-05-18", "Starter SaaS License", 5, 500.00, 2500.00),
        ("2026-05-28", "Custom Integration Service", 1, 3500.00, 3500.00),
        ("2026-06-02", "Enterprise Cloud License", 1, 5000.00, 5000.00),
        ("2026-06-14", "Starter SaaS License", 10, 500.00, 5000.00),
        ("2026-06-20", "Enterprise Cloud License", 3, 5000.00, 15000.00),
        ("2026-07-02", "Starter SaaS License", 4, 500.00, 2000.00),
    ]
    cursor.executemany(
        "INSERT INTO sales (date, product, quantity, unit_price, total_amount) VALUES (?, ?, ?, ?, ?);",
        sales_data
    )
    
    # Commit changes saves all the insert statements to the file.
    conn.commit()
    print("Database seeded with sample data.")
    
    # =========================================================================
    # TEST RUN (VERIFICATION)
    # =========================================================================
    print("\nRunning a quick verification query:")
    cursor.execute("SELECT SUM(amount) FROM expenses WHERE category = 'Software';")
    total_software_expenses = cursor.fetchone()[0]
    print(f"-> Total Software Expenses in DB: ${total_software_expenses:,.2f}")
    
    # Close connection
    conn.close()
    print("Database connection closed.")

if __name__ == "__main__":
    initialize_database()
