-- =========================================================================
-- SQL SCHEMA FOR BIZWHISPERER CHAT HISTORY (SUPABASE POSTGRESQL)
-- =========================================================================
-- Paste this script directly into your Supabase project's SQL Editor and run it.
-- SQL Editor location: Supabase Dashboard -> Project -> SQL Editor -> New Query

-- 1. CREATE CONVERSATIONS TABLE
-- This table stores each unique chat session.
CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,                       -- Stores the unique session ID (e.g. timestamp string)
    title TEXT NOT NULL,                       -- Stores the chat title (e.g. first user question)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. CREATE MESSAGES TABLE
-- This table stores each message (both user questions and assistant answers).
CREATE TABLE IF NOT EXISTS messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- A unique UUID generated by PostgreSQL for each message row
    conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, 
                                               -- Links back to conversations. ID. If a conversation is deleted, 
                                               -- PostgreSQL will automatically delete all its messages.
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')), 
                                               -- Ensures role is either 'user' or 'assistant'
    content TEXT NOT NULL,                     -- The actual message content string
    thoughts JSONB,                            -- JSONB column to store the agent's intermediate steps/thoughts array
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. ENABLE INDEXES (FOR PERFORMANCE OPTIMIZATION)
-- Helps Supabase retrieve messages associated with a conversation_id extremely fast.
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);
